package db_beispiel;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christopher Bräuer
 */
public class GUI extends javax.swing.JFrame {

    DB_Anfragen db;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ausgabe = new javax.swing.JTable();
        button_loeschen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        button_hinzufuegen = new javax.swing.JButton();
        newPersonVorname = new javax.swing.JTextField();
        newPersonNachname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_bearbeiten = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datenbankbeispiel");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Namensliste");

        ausgabe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Person"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ausgabe);

        button_loeschen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_beispiel/ic_action_discard.png"))); // NOI18N
        button_loeschen.setText("Person löschen");
        button_loeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loeschenActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Person hinzufügen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, javax.swing.UIManager.getDefaults().getColor("Button.focus")));

        button_hinzufuegen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_beispiel/ic_action_add_person.png"))); // NOI18N
        button_hinzufuegen.setText("hinzufügen");
        button_hinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hinzufuegenActionPerformed(evt);
            }
        });

        jLabel4.setText("Vorname:");

        jLabel3.setText("Nachname:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(newPersonNachname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(button_hinzufuegen, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(27, 27, 27)
                            .addComponent(newPersonVorname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newPersonNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newPersonVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_hinzufuegen)
                .addContainerGap())
        );

        button_bearbeiten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_beispiel/ic_action_edit.png"))); // NOI18N
        button_bearbeiten.setText("Person bearbeiten");
        button_bearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bearbeitenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_loeschen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(button_bearbeiten))))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_loeschen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_bearbeiten)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_hinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hinzufuegenActionPerformed

        if (newPersonNachname.getText().trim().isEmpty() || newPersonVorname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sie müssen einen Vor- und Nachnamen eingeben!", "Fehler", JOptionPane.WARNING_MESSAGE);
        } else {
            db.addName(newPersonNachname.getText().trim(), newPersonVorname.getText().trim());
            JOptionPane.showMessageDialog(this, "Die Person wurde hinzugefügt!", "Erfolg", JOptionPane.INFORMATION_MESSAGE);            
            daten_anzeigen();
        }
    }//GEN-LAST:event_button_hinzufuegenActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        daten_anzeigen();

    }//GEN-LAST:event_formComponentShown

    private void button_loeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loeschenActionPerformed

        if (ausgabe.getSelectedRow() >= 0) {
            db.delName(ausgabe.getValueAt(ausgabe.getSelectedRow(), 0).toString()); // 0 --> erste Spalte
            daten_anzeigen();
        } else {
            JOptionPane.showMessageDialog(this, "Sie müssen zuerst eine Person auswählen.", "Hinweis", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_button_loeschenActionPerformed

    private void button_bearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bearbeitenActionPerformed

        if (ausgabe.getSelectedRow() >= 0) {
            String person_alt = ausgabe.getValueAt(ausgabe.getSelectedRow(), 0).toString();
            GUI_PersonEdit frage = new GUI_PersonEdit(this, true, person_alt); // 0 --> erste Spalte
            frage.setVisible(true);
            String[] person_neu = frage.getReturnValue();
            if(person_neu != null){
                db.updateName(person_alt.split(", "), person_neu);
                daten_anzeigen();
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Sie müssen zuerst eine Person auswählen.", "Hinweis", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_button_bearbeitenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ausgabe;
    private javax.swing.JButton button_bearbeiten;
    private javax.swing.JButton button_hinzufuegen;
    private javax.swing.JButton button_loeschen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newPersonNachname;
    private javax.swing.JTextField newPersonVorname;
    // End of variables declaration//GEN-END:variables

    private void daten_anzeigen() {
        // Datenbankobjekt erstellen
        db = new DB_Anfragen();

        // Namen aus DB holen
        final ArrayList<String> namensliste = db.getNamensliste();

        // Namen anzeigen
        DefaultTableModel myListModel = new DefaultTableModel(new String[]{ausgabe.getModel().getColumnName(0)}, namensliste.size());

        for (int i = 0; i < namensliste.size(); i++) {
            myListModel.setValueAt(namensliste.get(i), i, 0);
        }

        ausgabe.setModel(myListModel);

        // DB-Verbindung schließen
        db.db_close();
    }
}
